name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run on PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job runs before deployment
    if: success()  # Only run if the build job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Heroku CLI
        uses: akshnz/heroku-cli-action@v0.1.0

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku login --api-key $HEROKU_API_KEY

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/your-heroku-app.git
          git push heroku main  # Push to Heroku to trigger the deployment
